//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP
{
    using System;
    using System.Collections.Generic;
    
    public partial class activity_log
    {
        public int log_id { get; set; }
        public int victim_id { get; set; }
        public string action_type { get; set; }
        public string action_details { get; set; }
        public Nullable<System.DateTime> action_time { get; set; }
    
        public virtual victim victim { get; set; }
    }
}
