//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class virus_dbEntities2 : DbContext
    {
        private static virus_dbEntities2 _context;
        public virus_dbEntities2()
            : base("name=virus_dbEntities2")
        {
        }
    
        public static virus_dbEntities2 GetContext()
        {
            if (_context == null)
                _context = new virus_dbEntities2();

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<activity_log> activity_log { get; set; }
        public virtual DbSet<encrypted_file> encrypted_file { get; set; }
        public virtual DbSet<victim> victims { get; set; }
    }
}
