//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP
{
    using System;
    using System.Collections.Generic;
    
    public partial class encrypted_file
    {
        public int file_id { get; set; }
        public int victim_id { get; set; }
        public string file_path { get; set; }
        public string file_ext { get; set; }
        public Nullable<long> file_size { get; set; }
    
        public virtual victim victim { get; set; }
    }
}
