//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CP
{
    using System;
    using System.Collections.Generic;
    
    public partial class victim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public victim()
        {
            this.activity_log = new HashSet<activity_log>();
            this.encrypted_file = new HashSet<encrypted_file>();
        }
    
        public int victim_id { get; set; }
        public string computer_name { get; set; }
        public string user_name { get; set; }
        public string encryption_key { get; set; }
        public Nullable<int> files_count { get; set; }
        public Nullable<System.DateTime> infected_time { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activity_log> activity_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<encrypted_file> encrypted_file { get; set; }
    }
}
